### ISSUE TITLE
cleaver watch no longer works

### ISSUE THREAD

**Issue by natelaws** [jdan/cleaver#113]
It looks like the fix to #105 may have broken the watch functionality.

```
> cleaver watch --debug t.md
Watching for changes on t.md. Ctrl-C to abort.
  cleaver loaded input document +0ms
  helper read /usr/local/lib/node_modules/cleaver/templates/layout.mustache +1ms
  helper read /usr/local/lib/node_modules/cleaver/templates/author.mustache +0ms
  helper read /usr/local/lib/node_modules/cleaver/resources/default.css +1ms
  helper read /usr/local/lib/node_modules/cleaver/templates/default.mustache +0ms
  cleaver loaded templates +0ms
  cleaver parsed options +4ms
  helper read /usr/local/lib/node_modules/cleaver/resources/github.css +3ms
  helper read /usr/local/lib/node_modules/cleaver/resources/script.js +0ms
  cleaver loaded static assets +0ms
  cleaver rendered slides +3ms
  cleaver rendered presentation +7ms
Rebuilding: Sat Apr 18 2015 19:27:00 GMT-0400 (EDT)

/usr/local/lib/node_modules/cleaver/lib/index.js:29
    debug.enable('*');
          ^
TypeError: Object function enabled() {

    var self = enabled;

    // set `diff` timestamp
    var curr = +new Date();
    var ms = curr - (prevTime || curr);
    self.diff = ms;
    self.prev = prevTime;
    self.curr = curr;
    prevTime = curr;

    // add the `color` if not set
    if (null == self.useColors) self.useColors = exports.useColors();
    if (null == self.color && self.useColors) self.color = selectColor();

    var args = Array.prototype.slice.call(arguments);

    args[0] = exports.coerce(args[0]);

    if ('string' !== typeof args[0]) {
      // anything else let's inspect with %o
      args = ['%o'].concat(args);
    }

    // apply any `formatters` transformations
    var index = 0;
    args[0] = args[0].replace(/%([a-z%])/g, function(match, format) {
      // if we encounter an escaped % then don't increase the array index
      if (match === '%%') return match;
      index++;
      var formatter = exports.formatters[format];
      if ('function' === typeof formatter) {
        var val = args[index];
        match = formatter.call(self, val);

        // now we need to remove `args[index]` since it's inlined in the `format`
        args.splice(index, 1);
        index--;
      }
      return match;
    });

    if ('function' === typeof exports.formatArgs) {
      args = exports.formatArgs.apply(self, args);
    }
    var logFn = enabled.log || exports.log || console.log.bind(console);
    logFn.apply(self, args);
  } has no method 'enable'
    at new Cleaver (/usr/local/lib/node_modules/cleaver/lib/index.js:29:11)
    at /usr/local/lib/node_modules/cleaver/bin/cleaver:21:26
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

Taking out the debug flag I get this message
```
> cleaver watch t.md        
Watching for changes on t.md. Ctrl-C to abort.
Rebuilding: Sat Apr 18 2015 19:37:17 GMT-0400 (EDT)
!! undefined is not a function
```

**Comment by jdan** [comment]
:( Oh no. I'll look into this ASAP.
