### ISSUE TITLE
Watch throws TypeError

### ISSUE THREAD

**Issue by mike-ward** [jdan/cleaver#140]
```
cleaver -V
0.7.5

cleaver watch slides.md
Watching for changes on slides.md. Ctrl-C to abort.
Also watching for changes on undefined
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at Object.fs.watchFile (fs.js:1315:25)
    at Command.<anonymous> (C:\Users\mike\AppData\Roaming\npm\node_modules\cleaver\bin\cleaver:81:10)
    at Command.<anonymous> (C:\Users\mike\AppData\Roaming\npm\node_modules\cleaver\node_modules\commander\index.js:249:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\mike\AppData\Roaming\npm\node_modules\cleaver\node_modules\commander\index.js:477:12)
    at Command.parse (C:\Users\mike\AppData\Roaming\npm\node_modules\cleaver\node_modules\commander\index.js:370:21)
    at Object.<anonymous> (C:\Users\mike\AppData\Roaming\npm\node_modules\cleaver\bin\cleaver:133:9)
```

**Comment by jdan** [comment]
Hey @mike-ward,

This was fixed in #136, which means an upgrade to cleaver should fix this :)

```
npm update -g cleaver
```

If this still crops up please let me know!
