### ISSUE TITLE
Watch throws an exception

### ISSUE THREAD

**Issue by cholick** [jdan/cleaver#97]
Using cleaver to generate a presentation works, but trying to watch throws an exception:

```
➜  tmp  cleaver watch present/basic.md
Watching for changes on present/basic.md. Ctrl-C to abort.
fs.js:434
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:434:11)
    at Object.fs.readFile (fs.js:227:6)
    at /Users/matt/.nvm/v0.11.13/lib/node_modules/cleaver/bin/cleaver:15:8
    at Array.forEach (native)
    at createAndSave (/Users/matt/.nvm/v0.11.13/lib/node_modules/cleaver/bin/cleaver:14:9)
    at Object.<anonymous> (/Users/matt/.nvm/v0.11.13/lib/node_modules/cleaver/bin/cleaver:98:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
```

I also tried running under node 0.10.x. basic.md is simple the example presentation from the documentation.

--debug produces no additional information.

**Comment by alanclarke** [comment]
@jdan issue appears to have returned in 0.7.5
